### ISSUE TITLE
日志解析

### ISSUE THREAD

**Issue by fWX228941** [fWX228941/project#23]
1.每次bindService 都返回false ，原因是因为没有注册，声明our application does not know which service to be bound. This is because either we didn't declare the service in the manifest file, or we declared it in the wrong way.											
参考：http://stackoverflow.com/questions/5307903/android-bind-service-returns-false-every-time
2.最常见的就是空指针的问题惹，现在就是出现各种崩溃现象不过是好事
3.bindService也有其使用规范，时序发生问题了，调用bindSerivice的context 还没有初始化完成（onCreate未执行完毕），导致连接不能够正常创建，而当使用回调方法来实现时，就意味着Activity已经初始化完毕，而链接建立成功，也自然可以得到service的实例，所以不会抛异常。
参考：http://blog.csdn.net/wonderful_eastar/article/details/51649433
4.日志忘记对比过去了，beyondCompare只要保证不是红色就是，就说逻辑上是没有问题的，既然没有问题也是不应该出现任何问题的。粗心大意很受伤啊！
5.替换资源文件后一定要clean一下，不然是不会替换资源文件的
6.extra  传递类型的时候一定要特别注意，尤其是int long 否则传递long 取int 会被指为0的，这不报错

**Comment by fWX228941** [comment]
1. eclipse创建android项目时，预览layout.xml文件时提示： This version of the rendering library is more recent than your version of ADT plug-in. Please update ADT plug-in，导致无法正常预览布局文件。问题根源：SDK版本过高，ADT版本过低
解决方案：http://jingyan.baidu.com/article/d621e8da0e0e052865913fae.html
2. Exception raised during rendering: java.lang.System.arraycopy 基本上就是ADT版本的问题，手动更新就是了。
解决方案：
http://stackoverflow.com/questions/24451490/exception-raised-during-rendering-java-lang-system-arraycopy
总之不升级ADT xml就会出现各种问题，ADT就是一个插件集合，没有各种插件，编程举步维艰。
3.当安装apk出现user_id错误则需要在源码中编译
当installl apk 时出现[INSTALL_FAILED_DEXOPT]则是odex问题
解决方法：http://blog.csdn.net/h3c4lenovo/article/details/8076585，找到未优化过的apk就成功了，目录在obj/APPS/xxx/package.apk.unaligned  (一定要小心不是unsigned否则会出现未签名错误)

4.
     1）java.lang.RuntimeException: Unable to start activity 
ComponentInfo{com.zte.dmo/com.zte.dmo.app.activity.DmoMainActivity}: android.view.InflateException: Binary XML file line #1: Error inflating class <unknown>
 2）Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class <unknown>
3）Caused by: java.lang.reflect.InvocationTargetException
4）Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x1/d=0x7f02000e a=-1 r=0x7f02000e}
原因：xml文件中无法引用第三方自定义文件，遗憾的是eclipse在编译，即使编程后都无法检测这个错误，所以一定要担心，尤其是移植代码的时候

5. java.lang.SecurityException: Binder invocation to an incorrect interface [AIDL客户端和服务器端，包名和服务名要保证一样才行]

6. 12-27 14:02:30.301 6405-6425/? E/AndroidRuntime: FATAL EXCEPTION: GotaSystem
                                                 android.content.res.Resources$NotFoundException: Resource ID #0x7f02001d
                                                     at android.content.res.Resources.getValue(Resources.java:1027)
                                                     at android.content.res.Resources.getDrawable(Resources.java:672)
                                                     at android.view.View.setBackgroundResource(View.java:14267)
													 
                                                     at com.zte.dmo.app.view.GotaOptionMenu.initMenu(GotaOptionMenu.java:170)
                                                     at com.zte.dmo.app.view.GotaOptionMenu.<init>(GotaOptionMenu.java:87)
													 
                                                     at com.zte.dmo.app.activity.DmoMainActivity.initMenuResources(DmoMainActivity.java:224)
                                                     at com.zte.dmo.app.activity.DmoMainActivity.init(DmoMainActivity.java:216)
                                                     at com.zte.dmo.app.activity.DmoMainActivity.access$400(DmoMainActivity.java:64)
                                                     at com.zte.dmo.app.activity.DmoMainActivity$3.onSuccess(DmoMainActivity.java:189)
                                                     at com.zte.dmo.app.activity.DmoMainActivity$3.onSuccess(DmoMainActivity.java:182)
                                                     at com.zte.dmo.core.common.GotaSystem$3.isDmoActived(GotaSystem.java:320)
                                                     at com.zte.dmo.core.dmo.DMOPhone.handleMessage(DMOPhone.java:208)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:137)
                                                     at android.os.HandlerThread.run(HandlerThread.java:60)
资源文件找不到，odex文件导致的，解决方法，在mk编译文件中把odex文件的生成项false掉

7. 12-27 15:48:24.051 2244-2264/? E/AndroidRuntime: FATAL EXCEPTION: GotaSystem
                                                 android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
                                                     at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:4611)
                                                     at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:835)
                                                     at android.view.View.requestLayout(View.java:15217)
                                                     at android.view.View.requestLayout(View.java:15217)
                                                     at android.view.View.requestLayout(View.java:15217)
                                                     at android.view.View.requestLayout(View.java:15217)
                                                     at android.view.View.requestLayout(View.java:15217)
                                                     at android.widget.TextView.checkForRelayout(TextView.java:6309)
                                                     at android.widget.TextView.setText(TextView.java:3547)
                                                     at android.widget.TextView.setText(TextView.java:3405)
                                                     at android.widget.TextView.setText(TextView.java:3380)
                                                     at com.zte.dmo.app.activity.DmoMainActivity.initView(DmoMainActivity.java:370)
                                                     at com.zte.dmo.app.activity.DmoMainActivity.init(DmoMainActivity.java:212)
                                                     at com.zte.dmo.app.activity.DmoMainActivity.access$400(DmoMainActivity.java:64)
                                                     at com.zte.dmo.app.activity.DmoMainActivity$3.onSuccess(DmoMainActivity.java:184)
                                                     at com.zte.dmo.app.activity.DmoMainActivity$3.onSuccess(DmoMainActivity.java:177)
                                                     at com.zte.dmo.core.common.GotaSystem$3.isDmoActived(GotaSystem.java:320)
                                                     at com.zte.dmo.core.dmo.DMOPhone.handleMessage(DMOPhone.java:208)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:137)
                                                     at android.os.HandlerThread.run(HandlerThread.java:60)

正解：http://daydayup1989.iteye.com/blog/784831

8.    
                    java.lang.RuntimeException: Unable to instantiate application com.zte.dmo.ZteGotaLteApp: java.lang.ClassNotFoundException: com.zte.dmo.ZteGotaLteApp
                                              Caused by: java.lang.ClassNotFoundException: com.zte.dmo.ZteGotaLteApp
正解：xml文件中路径不正确，导致找不到类







9. java heap space Exception in checkAndLoadTargetData
http://www.myexception.cn/eclipse/1598028.html  内存不足的原因
10. 
No private recovery resources for TARGET_DEVICE msm8625
make: 放弃循环依赖 out/targer/common/obj/JAVA_LIBRARIES/ext_intermediates/classes-full-debug.jar <- out/target
/common/obj/JAVA_LIBRARIES/com.qrd.plugin.feature_query_intermediates/javalib.jar

11.如果出现error token  
则一般是少了一个括号，逗号什么的

12.                                                    Caused by: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=org.gotapropertyutils.AIDL_SERVICE }
版本差异，5.0必须显式声明要启动的service 
http://blog.csdn.net/shenzhonglaoxu/article/details/42675287

13. Caused by: java.lang.ClassNotFoundException:
Xml 文件的类路径错误会导致额，而且是会导致直接崩溃的

14. java.lang.IllegalArgumentException: Window type can not be changed after the window is added.
http://www.it1352.com/81335.html
http://stackoverflow.com/questions/31081968/illegalargumentexception-window-type-can-not-be-changed-after-the-window-is-add
http://macleo.iteye.com/blog/1747465

15.crash 日志记得找fatal
16. 2017-03-23 15:23:11 - Dex Loader] Unable to execute dex: Multiple dex files define Landroid/support/v4/media/TransportController;
Jar 包重复导致 删除重复jar包即可

17.  版本差异问题
                                                       java.lang.SecurityException: Permission Denial: broadcastIntent() requesting a sticky broadcast from pid=2215, uid=10026 requires android.permission.BROADCAST_STICKY
粘性广播，需要权限

18.从非activity的外部界面隐式启动一个activity，需要添加
                                                         android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?


19. Android Gradle Could not reserve enough space for object heap
https://stackoverflow.com/questions/30045417/android-gradle-could-not-reserve-enough-space-for-object-heap

org.gradle.jvmargs=-XX\:MaxHeapSize\=256m -Xmx256m

20．由于这台计算机没有远程桌面客户端访问许可证，远程会话被中断
http://blog.csdn.net/xinma/article/details/40145371

21.签名的时候出现cannot resove 则说明是签名的密码错误

22.
android.app.SuperNotCalledException: Activity {com.zte.dmo/com.zte.dmo.app.activity.DmoMainActivity} did not call through to super.onDestroy()
覆写的Activity需要重写并调用super.onDestroy()方法

23. E/AndroidRuntime(2988): android.view.InflateException: Binary XML file line #2: Error inflating class com.zte.pdt.ui.message.MessageInfoLayout
03-22 09:04:47.228: E/AndroidRuntime(2988): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757)
03-22 09:04:47.228: E/AndroidRuntime(2988): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
03-22 09:04:47.228: E/AndroidRuntime(2988): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
尤其是自定义布局修改名称的时候，布局文件一定要修改

24.解决Android Studio : INSTALL_FAILED_OLDER_SDK 
Manifest.xml 文件的sdk 版本有问题
